### ISSUE TITLE
地図を秋葉原を中心に自動で開くようにする

### ISSUE THREAD

**Issue by TaroNakasendo** [find-tech/straggler-search-system#30]
地図の保存はされるが、秋葉原あたりの地図が結果として表示されるようにしたい。
map.htmlを開くと、北極が表示されている。秋葉原を中心に表示できますか？
chromeかedgeまたはMacのsafariあたりで...(TKinterのウィンドウ内だとベストですが...)

**Comment by TaroNakasendo** [comment]
それか、地図自体を画像(jpg, pngなど)にして保存することができれば、それをこちらで作ったWindowで表示させることはできそうです。

**Comment by sasshi-i** [comment]
地図の表示位置については、受け取ったdfの初めのレコードのカメラIDを元に緯度経度を算出し、設定されます。
今どのような値を渡していますでしょうか。

**Comment by TaroNakasendo** [comment]
いただいたcsvを読み込ませているのですが、、、

**Comment by TaroNakasendo** [comment]
カメラのいどけい

**Comment by TaroNakasendo** [comment]
カメラ定義ファイルのカメラの緯度と経度が逆だったので、入れ替えたのですが、それが影響しているかもしれません。

**Comment by TaroNakasendo** [comment]
緯度と経度を入れ替えたら表示できました。

**Comment by TaroNakasendo** [comment]
ブラウザで結果を開けるようになりました
